# Generated by Django 4.1.5 on 2023-01-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('student_number', models.IntegerField(max_length=30)),
                ('guardian_name', models.CharField(max_length=30)),
                ('guardian_contact', models.CharField(max_length=30)),
            ],
        ),
    ]
