# Generated by Django 4.1.5 on 2023-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClinicRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time_of_visit', models.DateTimeField()),
                ('student_name', models.CharField(max_length=30)),
                ('student_number', models.IntegerField(max_length=30)),
                ('year_level_and_course', models.CharField(max_length=30)),
            ],
        ),
    ]
