# Generated by Django 4.1.5 on 2023-01-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_dailyclinicrecords_date_and_time_of_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClinicRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time_of_visit', models.CharField(max_length=30)),
                ('chief_complaints', models.CharField(max_length=30)),
                ('treatments', models.IntegerField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
