# Generated by Django 4.1.5 on 2023-01-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentclinicrecords_student_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='studentclinicrecords',
            name='student_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rec', to='students.student'),
        ),
    ]
