# Generated by Django 4.1.5 on 2023-01-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_first_name_alter_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_created',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
