# Generated by Django 4.1.5 on 2023-01-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_created',
            field=models.CharField(default='2023', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentclinicrecords',
            name='date_and_time_of_visit',
            field=models.DateTimeField(),
        ),
    ]
