# Generated by Django 4.1.5 on 2023-01-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclinicrecords',
            name='date_and_time_of_visit',
            field=models.CharField(max_length=30),
        ),
    ]
